package com.hams.enums;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CHECKED_IN,
    CONSULTATION_COMPLETED,
    PRESCRIPTION_READY,
    GENERAL
}
